name: Vim Help Tag

on:
  push:
    paths:
      - README.md

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v3
      - name: Generate vimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: barbecue
          description: A VS Code like winbar for Neovim
          version: NVIM v0.8.0
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          file_pattern: doc/lualine.txt
          commit_message: |
            chore(docs): generate vimdoc

            Convert `README.md` at project root to vimdoc located at
            `doc/barbecue.txt`.

            Author: GitHub Workflow
